name: Stable JavaDoc

on:
  push #:
#    branches:
#      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Generate JavaDoc files
        run: |
          mkdir public
          mvn javadoc:javadoc
          ls -l
          ls /home/runner/work/delta-sqc/delta-sqc/target/site/apidocs
          cp /home/runner/work/delta-sqc/delta-sqc/target/site/apidocs/* public/*
          ls docs/

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: documentation/stable
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}