name: Stable JavaDoc

on:
  push #:
#    branches:
#      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Gen dummy page
        run: |
          mkdir public
          mvn javadoc:javadoc
          mv target/apidocs/* docs/*
          ls docs/

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: docs/stable
          build_dir: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}